PLAYGROUND_CHAT_URL = "https://api.ntth.ai/v1/chat"
PLAYGROUND_MODEL_ID = "ed5b6725-9aa2-49b4-b2b3-add71e99fe5e"

PLAYGROUND_APP_ID = "b4b98c36-e09f-49bd-870a-f0a0d3044100"
PLAYGROUND_APP_SECRET = "avhd6S=,:tv!6c[|uvU5,kmw^JlOaH4W$pjo"
